---

- name: Install memcached server
  run_once: true
  apt: name=php-memcached state=present

- name: Daemon copy
  run_once: true
  template: src=etc/init.d/memcached dest=/etc/init.d/memcached owner=root group=root mode=0755

- name: Do memcached config
  run_once: true
  template: src=etc/memcached.conf dest=/etc/memcached.conf owner=root group=root mode=0644
  notify: php-memcached restart